services:

  postgres:
    image: pgvector/pgvector:pg18
    container_name: brife-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5

  app:
    build: .
    container_name: brife-app
    ports:
      - "8080:8085"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      GOOGLE_APPLICATION_CREDENTIALS: /app/google-credentials.json
    volumes:
      - ${GOOGLE_CREDENTIALS_PATH}:/app/google-credentials.json:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: