spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  autoconfigure:
    exclude:
#      - org.springframework.ai.model.vertex.autoconfigure.gemini.VertexAiGeminiAutoConfiguration
#      - org.springframework.ai.model.vertex.autoconfigure.embedding.VertexAiEmbeddingAutoConfiguration
      - org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration